version: 2.1

commands:
  setup:
    steps:
      - checkout
      - run:
          name: 'Login to npm'
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: yarn install --frozen-lockfile

executors:
  node:
    docker:
      - image: circleci/node:14.17.3

jobs:
  lint-build-test:
    executor: node
    steps:
      - setup
      - run:
          name: Lint source code
          command: yarn lint
      - run:
          name: Start server and test
          command: yarn test:custom
      - run:
          name: Build distribution files
          command: yarn build
      - persist_to_workspace:
          root: .
          paths: .

  publish-release:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Release
          command: yarn semantic-release

workflows:
  test-and-publish:
    jobs:
      - lint-build-test
      - publish-release:
          filters:
            branches:
              only: master
          requires:
            - lint-build-test
